server:
  port: 9999

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(description=(address_list=(address=(host=127.0.0.1)(protocol=tcp)(port=15215)))(connect_data=(service_name=zhwgdb)))
    username: TABLEQUERYMANAGER
    password: jk$sdLT#yx#6354